# Pre-commit hooks.
# python -m pip install pre-commit
# pre-commit install
# pre-commit run --all-files

repos:

  # Format Python
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black

  # Sort imports
  - repo: https://github.com/timothycrosley/isort
    rev: 5.6.4
    hooks:
      - id: isort
        additional_dependencies: ["toml"]

  # Lint Python
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
